# Locations of important files and folders
LogFile:          "data/log backend.txt"        # Log file for the backend. It contains informational and error messages.
BlockchainMain:   "data/blockchain main/"       # Blockchain main stores the end-users blockchain data. It contains meta data of shared files, profile data, and social interactions.
BlockchainGlobal: "data/blockchain global/"     # Blockchain global caches blockchain data from global users. Empty to disable.
WarehouseMain:    "data/warehouse main/"        # Warehouse main stores the actual data of files shared by the end-user.
SearchIndex:      "data/search index/"          # Local search index of blockchain records. Empty to disable.
GeoIPDatabase:    "data/GeoLite2-City.mmdb"     # GeoLite2 City database to provide GeoIP information.
DataFolder:       "data/"                       # Data folder.

# Listen defines all IP:Port combinations to listen on. If empty, it will listen on all IPs automatically on available ports.
# IPv6 must be in the form "[IPv6]:Port". This setting is only recommended to be set on servers.
Listen: []

# Count of workers to process incoming raw packets. Default 2.
ListenWorkers: 0

# Count of workers to process incoming lite packets. Default 2.
ListenWorkersLite: 0

# AutoUpdateSeedList enables auto update of the seed list.
AutoUpdateSeedList: true

# Initial peer seed list. If AutoUpdateSeedList is enabled then any changes will be overwritten on update.
SeedListVersion: 1
SeedList:
  - PublicKey: 031a4a703145147edea525ce027bec68f76743e6e1e47817996961d489fda01431 # 1.peernet.network
    Address: ["185.254.123.112:112","[2a0c:1880::112]:112"]

# Connection settings
EnableUPnP:     true    # Enables support for UPnP.
LocalFirewall:  false   # Indicates that a local firewall may drop unsolicited incoming packets.

# PortForward specifies an external port that was manually forwarded by the user. All listening IPs must have that same port number forwarded!
# If this setting is invalid, it will prohibit other peers from connecting. If set, it automatically disables UPnP.
PortForward: 0          # Default not set.

# Global blockchain cache limits
CacheMaxBlockSize:    50096  # Max block size to accept in bytes.
CacheMaxBlockCount:   256   # Max block count to cache per peer.
LimitTotalRecords:    0     # Record count limit. 0 = unlimited. Max Records * Max Block Size = Size Limit.
